version: '3'
services:
  weblate:
    image: weblate/weblate:5
    volumes:
    - weblate-data:/app/data
    - weblate-cache:/app/cache
    env_file:
    - ./environment
    - ./stack.env
    ports:
      - 8880:8080
    restart: always
    depends_on:
    - database
    - cache
  database:
    image: postgres:15-alpine
    env_file:
    - ./environment
    - ./stack.env
    volumes:
    - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:7-alpine
    restart: always
    command: [redis-server, --save, '60', '1']
    volumes:
    - redis-data:/data
volumes:
  weblate-cache: {}
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
